### ISSUE TITLE
Teams output is just a link as text (not even a recognized as a link)

### ISSUE THREAD

**Issue by medea61** [poshbotio/PoshBot.Giphy#1]
At the moment the output to Teams is just an URL that is not beeing resolved/displayed as a picture in chat. It is just a link as text. So to use it you have to copy it manually which renders this plugin pretty much useless in Teams.

## Current Behavior
Bot reply is just a link as text.

## Expected Behavior
Either return a link or more preferably display the gif.

## Possible Solution
Change output to allowed [bot text formats](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-text-formats) according to the docs.

**Comment by devblackops** [comment]
Thanks @medea61!

`v1.0.3` has been [published to PSGallery](https://www.powershellgallery.com/packages/PoshBot.Giphy/1.0.3) with your fix.
